# Generated by Django 5.1.4 on 2024-12-17 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('record_number', models.CharField(max_length=30)),
                ('registration_number', models.CharField(max_length=30)),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('country_of_arrival', models.CharField(max_length=30)),
                ('place_of_arrival', models.CharField(max_length=30)),
                ('city_of_arrival', models.CharField(max_length=30)),
                ('VIN_number', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=100)),
                ('waybill', models.FileField(upload_to='')),
                ('damage_report', models.FileField(upload_to='')),
                ('photo_car', models.FileField(upload_to='')),
                ('photo_VIN', models.FileField(upload_to='')),
                ('photo_area', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('profile_image', models.ImageField(upload_to='profile_images/')),
                ('category', models.CharField(choices=[('ST', 'Student'), ('TE', 'Teacher'), ('OT', 'Other')], default='ST', max_length=2)),
            ],
        ),
    ]
