# Generated by Django 5.1.4 on 2025-01-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_department_remove_person_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='userType',
            field=models.CharField(choices=[('AGENT', 'Agent'), ('ADMIN', 'Admin')], default='AGENT', max_length=5),
        ),
    ]
