# Generated by Django 5.1.4 on 2025-01-17 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_communicationmodel_othermodel_preparationmodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportmodel',
            old_name='Registration_number',
            new_name='registration_number',
        ),
    ]
