# Generated by Django 5.1.4 on 2025-01-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_person_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='reclamationType',
            field=models.CharField(choices=[('C&D', 'Claim & Damage'), ('TRN', 'Transportation'), ('VPR', 'Vehicke preparation'), ('CMN', 'Comunication'), ('OTH', 'Other')], default='OTH', max_length=3),
        ),
    ]
