# Generated by Django 5.1.4 on 2025-01-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_communicationmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimmodel',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('opened', 'Opened'), ('archive', 'Archive')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='communicationmodel',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('opened', 'Opened'), ('archive', 'Archive')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='othermodel',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('opened', 'Opened'), ('archive', 'Archive')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='preparationmodel',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('opened', 'Opened'), ('archive', 'Archive')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='transportmodel',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('opened', 'Opened'), ('archive', 'Archive')], default='new', max_length=20),
        ),
    ]
