# Generated by Django 5.1.4 on 2025-01-27 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_department_email_department_reclamationtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='userType',
            new_name='user_type',
        ),
    ]
