# Generated by Django 5.1.4 on 2025-01-29 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_communicationmodel_date'),
        ('main', '0005_rename_usertype_person_user_type'),
    ]

    operations = [
    ]
