# Generated by Django 5.1.4 on 2025-01-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_claimmodel_status_communicationmodel_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimmodel',
            name='damage_report',
            field=models.FileField(upload_to='temp/'),
        ),
        migrations.AlterField(
            model_name='claimmodel',
            name='photo_VIN',
            field=models.FileField(upload_to='temp/'),
        ),
        migrations.AlterField(
            model_name='claimmodel',
            name='photo_area',
            field=models.FileField(upload_to='temp/'),
        ),
        migrations.AlterField(
            model_name='claimmodel',
            name='photo_car',
            field=models.FileField(upload_to='temp/'),
        ),
        migrations.AlterField(
            model_name='claimmodel',
            name='waybill',
            field=models.FileField(upload_to='temp/'),
        ),
        migrations.AlterField(
            model_name='communicationmodel',
            name='photo',
            field=models.FileField(upload_to='temp/'),
        ),
        migrations.AlterField(
            model_name='othermodel',
            name='photo',
            field=models.FileField(upload_to='temp/'),
        ),
        migrations.AlterField(
            model_name='preparationmodel',
            name='photo',
            field=models.FileField(upload_to='temp/'),
        ),
        migrations.AlterField(
            model_name='transportmodel',
            name='photo',
            field=models.FileField(upload_to='temp/'),
        ),
    ]
