from django.utils.translation import gettext_lazy as _
NATURE_OF_DAMAGE = [
    ("BR", _("Burned")),
    ("CA", _("Broken, teared off, cracked")),
    ("CD", _("Cut, torn")),
    ("CE", _("Pierced, cut")),
    ("EC", _("Paint peeled")),
    ("EN", _("Dented")),
    ("MA", _("Missing")),
    ("PR", _("Damaged")),
    ("RF", _(" Scratched, scuffed")),
    ("TA", _("Stained")),
    ("XX", _("Not specified"))
]




PLACE_OF_DAMAGE = [
    ("00", _("Nothing")),
    ("01", _("Front wing")),
    ("02", _("Front bumper")),
    ("03", _("Hood")),
    ("04", _("Front bumper protection strip")),
    ("05", _("A pillar")),
    ("06", _("Roof")),
    ("07", _("Roof window")),
    ("08", _("Roof rack")),
    ("09", _("Hinged roof")),
    ("10", _("Windscreen")),
    ("11", _("Trunk door")),
    ("12", _("Rear bumper")),
    ("13", _("Tail board")),
    ("14", _("Rear bumper protection strip")),
    ("15", _("Driver door - lining")),
    ("16", _("Driver door - door sill")),
    ("17", _("Door handle - front")),
    ("18", _("Door handle - rear")),
    ("19", _("Puncture repair kit")),
    ("20", _("Immobilizer code card")),
    ("21", _("Radio antenna")),
    ("22", _("Dirt traps")),
    ("23", _("Windshield washers / Headlight wipers")),
    ("24", _("Front wipers")),
    ("25", _("Rear wiper")),
    ("26", _("Rear spoiler")),
    ("27", _("Decorative wheel covers")),
    ("28", _("Additional floor mats - set")),
    ("29", _("User manual")),
    ("30", _("Right rearview mirror")),
    ("31", _("Right front fender")),
    ("32", _("Right front wheel: rim")),
    ("33", _("Right front wheel: tire")),
    ("34", _("Right wheel arch")),
    ("35", _("Right rear fender and C pillar")),
    ("36", _("Right front door")),
    ("37", _("Right rear door")),
    ("38", _("Right side panel (utility vehicle)")),
    ("39", _("Protective moldings - right side")),
    ("40", _("Front turn signals")),
    ("41", _("Fixed front glass left/right (for 36/56)")),
    ("42", _("Exhaust")),
    ("43", _("Tow eye cover front/rear")),
    ("44", _("Tools + bag")),
    ("45", _("Miscellaneous")),
    ("46", _("Keys")),
    ("47", _("Radiator grille")),
    ("48", _("Rear fog lights")),
    ("49", _("Third brake light")),
    ("50", _("Left rearview mirror")),
    ("51", _("Left front fender")),
    ("52", _("Left front wheel: rim")),
    ("53", _("Left front wheel: tire")),
    ("54", _("Left wheel arch")),
    ("55", _("left rear fender and C pillar")),
    ("56", _("Left front door")),
    ("57", _("Left rear door")),
    ("58", _("Left side panel (utility vehicle)")),
    ("59", _("Protective moldings - left side")),
    ("60", _("Fuel filter / cable cap")),
    ("61", _("Logo / emblem")),
    ("62", _("Carpet / mat in battery compartment")),
    ("63", _("License plate lighting")),
    ("64", _("Charging cable (electric vehicle)")),
    ("65", _("Rear lights")),
    ("66", _("Fixed rear glass left / right (for 37 / 57) + C pillar")),
    ("67", _("Rear side glass (for 48 / 58)")),
    ("68", _("Remote control key")),
    ("69", _("Door locks")),
    ("70", _("Center pillar")),
    ("71", _("Speakers")),
    ("72", _("Front / rear seats")),
    ("73", _("Right rear wheel: rim")),
    ("74", _("Right rear wheel: tire")),
    ("75", _("Side turn signals")),
    ("76", _("Headlights")),
    ("77", _("Front fog lights")),
    ("78", _("Rear shelf")),
    ("79", _("Vehicle kit")),
    ("80", _("Rear glass")),
    ("81", _("Wheel wrench")),
    ("82", _("Front side windows (for 36 / 56)")),
    ("83", _("Rear side windows (for 37 / 57)")),
    ("84", _("Lighter")),
    ("85", _("Navigation, CD-ROM, remote control")),
    ("86", _("Radio, radio accessories")),
    ("87", _("CD changer")),
    ("88", _("Front headrests")),
    ("89", _("Rear headrests + middle")),
    ("90", _("Safety key extension")),
    ("91", _("FFA/DC41")),
    ("92", _("Jack (kit)")),
    ("93", _("Left rear wheel: rim")),
    ("94", _("Left rear wheel: tire")),
    ("95", _("Spare tire"))
]

STATUS_CHOICES = [
        ('new', _('New')),
        ('opened', _('Opened')),
        ('archive', _('Archive')),
    ]


REPORT_TYPES = [
    ('CL', _("Claim & Damage")),
    ('CM', _("Communication")),
    ('TR', _("Transport")),
    ('VP', _("Vehicle Preparation")),
    ('OT', _("Other"))
]