NATURE_OF_DAMAGE = [
    ("BR", "Burned"),
    ("CA", "Broken, teared off, cracked"),
    ("CD", "Cut, torn"),
    ("CE", "Pierced, cut"),
    ("EC", "Paint peeled"),
    ("EN", "Dented"),
    ("MA", "Missing"),
    ("PR", "Damaged"),
    ("RF", " Scratched, scuffed"),
    ("TA", "Stained"),
    ("XX", "Not specified")
]




PLACE_OF_DAMAGE = [
    ("00", "Nothing"),
    ("01", "Front wing"),
    ("02", "Front bumper"),
    ("03", "Hood"),
    ("04", "Front bumper protection strip"),
    ("05", "A pillar"),
    ("06", "Roof"),
    ("07", "Roof window"),
    ("08", "Roof rack"),
    ("09", "Hinged roof"),
    ("10", "Windscreen"),
    ("11", "Trunk door"),
    ("12", "Rear bumper"),
    ("13", "Tail board"),
    ("14", "Rear bumper protection strip"),
    ("15", "Driver door - lining"),
    ("16", "Driver door - door sill"),
    ("17", "Door handle - front"),
    ("18", "Door handle - rear"),
    ("19", "Puncture repair kit"),
    ("20", "Immobilizer code card"),
    ("21", "Radio antenna"),
    ("22", "Dirt traps"),
    ("23", "Windshield washers / Headlight wipers"),
    ("24", "Front wipers"),
    ("25", "Rear wiper"),
    ("26", "Rear spoiler"),
    ("27", "Decorative wheel covers"),
    ("28", "Additional floor mats - set"),
    ("29", "User manual"),
    ("30", "Right rearview mirror"),
    ("31", "Right front fender"),
    ("32", "Right front wheel: rim"),
    ("33", "Right front wheel: tire"),
    ("34", "Right wheel arch"),
    ("35", "Right rear fender and C pillar"),
    ("36", "Right front door"),
    ("37", "Right rear door"),
    ("38", "Right side panel (utility vehicle)"),
    ("39", "Protective moldings - right side"),
    ("40", "Front turn signals"),
    ("41", "Fixed front glass left/right (for 36/56)"),
    ("42", "Exhaust"),
    ("43", "Tow eye cover front/rear"),
    ("44", "Tools + bag"),
    ("45", "Miscellaneous"),
    ("46", "Keys"),
    ("47", "Radiator grille"),
    ("48", "Rear fog lights"),
    ("49", "Third brake light"),
    ("50", "Left rearview mirror"),
    ("51", "Left front fender"),
    ("52", "Left front wheel: rim"),
    ("53", "Left front wheel: tire"),
    ("54", "Left wheel arch"),
    ("55", "left rear fender and C pillar"),
    ("56", "Left front door"),
    ("57", "Left rear door"),
    ("58", "Left side panel (utility vehicle)"),
    ("59", "Protective moldings - left side"),
    ("60", "Fuel filter / cable cap"),
    ("61", "Logo / emblem"),
    ("62", "Carpet / mat in battery compartment"),
    ("63", "License plate lighting"),
    ("64", "Charging cable (electric vehicle)"),
    ("65", "Rear lights"),
    ("66", "Fixed rear glass left / right (for 37 / 57) + C pillar"),
    ("67", "Rear side glass (for 48 / 58)"),
    ("68", "Remote control key"),
    ("69", "Door locks"),
    ("70", "Center pillar"),
    ("71", "Speakers"),
    ("72", "Front / rear seats"),
    ("73", "Right rear wheel: rim"),
    ("74", "Right rear wheel: tire"),
    ("75", "Side turn signals"),
    ("76", "Headlights"),
    ("77", "Front fog lights"),
    ("78", "Rear shelf"),
    ("79", "Vehicle kit"),
    ("80", "Rear glass"),
    ("81", "Wheel wrench"),
    ("82", "Front side windows (for 36 / 56)"),
    ("83", "Rear side windows (for 37 / 57)"),
    ("84", "Lighter"),
    ("85", "Navigation, CD-ROM, remote control"),
    ("86", "Radio, radio accessories"),
    ("87", "CD changer"),
    ("88", "Front headrests"),
    ("89", "Rear headrests + middle"),
    ("90", "Safety key extension"),
    ("91", "FFA/DC41"),
    ("92", "Jack (kit)"),
    ("93", "Left rear wheel: rim"),
    ("94", "Left rear wheel: tire"),
    ("95", "Spare tire")
]
